// These will hide the middle of the three regex groups
export const foulSpanArray = [
	/(f)(uck)()/,
	/(sh)(it)()/,
	/(b)(it)(ch)/,
	/(c)(un)(t)/,
	/(ni)(gg)(a)/,
	/(ni)(gge)(r)/,
	/(p)(o)(rn)/,
	/((?:\W|^)d)(ic)(k)/,
	/((?:\W|^)a)(ss)(es)(?!\w)/,
	/((?:\W|^)a)(ss)(\W|$)/,
	/((?:\W|^)r)(ap)(e|ist|ing)/,
	/((?:\W|^)c)(u)(m)/,
	/((?:\W|^)t)(i)(ts)/,
	/(t)(it)(ties)/,
	/(c)(o)(ck[^an])/, // doesnt match 'cockney', 'cockatrice'
	/(wh)(or)(e)/,
	/(p)(us)(sy)/,
	/(s)(e)(x)/,
	/(d)(ic)(k)/,
	/(ret)(ar)(d)/,
	/(a)(ss)(hat|face|head|burger|hole)/,
	/((?:\W|^)a)(n)(al[^oy])/,
	/(pe)(n)(is)/,
	/(va)(gi)(na)/,
	/(dr)(u)(gs)/,
	/(mast)(urb)(at)/,
	/(dr)(u)(gs)/,
]