module.exports = [
	{
		"approved_at_utc": null,
		"subreddit": "AskReddit",
		"selftext": "",
		"user_reports": [],
		"saved": false,
		"mod_reason_title": null,
		"gilded": 4,
		"clicked": false,
		"title": "Rich people of reddit who married someone significantly poorer, what surprised you about their (previous) way of life?",
		"link_flair_richtext": [],
		"subreddit_name_prefixed": "r/AskReddit",
		"hidden": false,
		"pwls": 6,
		"link_flair_css_class": null,
		"downs": 0,
		"thumbnail_height": null,
		"parent_whitelist_status": "all_ads",
		"hide_score": false,
		"name": "t3_bxgldm",
		"quarantine": false,
		"link_flair_text_color": "dark",
		"upvote_ratio": 0.9,
		"author_flair_background_color": null,
		"subreddit_type": "public",
		"ups": 63425,
		"total_awards_received": 7,
		"media_embed": {},
		"thumbnail_width": null,
		"author_flair_template_id": null,
		"is_original_content": false,
		"author_fullname": "t2_kpkyt",
		"secure_media": null,
		"is_reddit_media_domain": false,
		"is_meta": false,
		"category": null,
		"secure_media_embed": {},
		"link_flair_text": null,
		"can_mod_post": false,
		"score": 63425,
		"approved_by": null,
		"thumbnail": "self",
		"edited": false,
		"author_flair_css_class": null,
		"author_flair_richtext": [],
		"gildings": {
			"gid_1": 3,
			"gid_2": 4
		},
		"content_categories": null,
		"is_self": true,
		"mod_note": null,
		"created": 1559855681,
		"link_flair_type": "text",
		"wls": 6,
		"banned_by": null,
		"author_flair_type": "text",
		"domain": "self.AskReddit",
		"selftext_html": null,
		"likes": null,
		"suggested_sort": null,
		"banned_at_utc": null,
		"view_count": null,
		"archived": false,
		"no_follow": false,
		"is_crosspostable": false,
		"pinned": false,
		"over_18": false,
		"all_awardings": [
			{
				"is_enabled": true,
				"count": 4,
				"subreddit_id": null,
				"description": "Gold Award",
				"icon_width": 512,
				"icon_url": "https://www.redditstatic.com/gold/awards/icon/gold_512.png",
				"days_of_premium": 7,
				"name": "Gold",
				"icon_height": 512,
				"resized_icons": [
					null
				],
				"days_of_drip_extension": 0,
				"award_type": "global",
				"coin_price": 500,
				"id": "gid_2",
				"coin_reward": 100
			},
			{
				"is_enabled": true,
				"count": 3,
				"subreddit_id": null,
				"description": "Silver Award",
				"icon_width": 512,
				"icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
				"days_of_premium": 0,
				"name": "Silver",
				"icon_height": 512,
				"resized_icons": [
					null
				],
				"days_of_drip_extension": 0,
				"award_type": "global",
				"coin_price": 100,
				"id": "gid_1",
				"coin_reward": 0
			}
		],
		"media": null,
		"media_only": false,
		"can_gild": false,
		"spoiler": false,
		"locked": false,
		"author_flair_text": null,
		"visited": false,
		"num_reports": null,
		"distinguished": null,
		"subreddit_id": "t5_2qh1i",
		"mod_reason_by": null,
		"removal_reason": null,
		"link_flair_background_color": "",
		"id": "bxgldm",
		"is_robot_indexable": true,
		"report_reasons": null,
		"author": "knakworst36",
		"num_crossposts": 6,
		"num_comments": 22707,
		"send_replies": true,
		"contest_mode": false,
		"author_patreon_flair": false,
		"author_flair_text_color": null,
		"permalink": "/r/AskReddit/comments/bxgldm/rich_people_of_reddit_who_married_someone/",
		"whitelist_status": "all_ads",
		"stickied": false,
		"url": "https://www.reddit.com/r/AskReddit/comments/bxgldm/rich_people_of_reddit_who_married_someone/",
		"subreddit_subscribers": 23152929,
		"created_utc": 1559826881,
		"mod_reports": [],
		"is_video": false
	},
	[
		{
			"total_awards_received": 0,
			"approved_at_utc": null,
			"ups": 785,
			"mod_reason_by": null,
			"banned_by": null,
			"author_flair_type": "text",
			"removal_reason": null,
			"link_id": "t3_bxgldm",
			"author_flair_template_id": null,
			"likes": null,
			"no_follow": false,
			"replies": {
				"kind": "Listing",
				"data": [
					null
				]
			},
			"user_reports": [],
			"saved": false,
			"id": "eq7fjta",
			"banned_at_utc": null,
			"mod_reason_title": null,
			"gilded": 0,
			"archived": false,
			"report_reasons": null,
			"author": "appleciders",
			"can_mod_post": false,
			"send_replies": true,
			"parent_id": "t3_bxgldm",
			"score": 785,
			"author_fullname": "t2_bcrbr",
			"approved_by": null,
			"all_awardings": [],
			"subreddit_id": "t5_2qh1i",
			"body": "Making financial decisions based around the three paycheck month.\n\nIf you're paid every two weeks, most months you get two paychecks, and all of your monthly bills and budgeting is based on those two paychecks. But twice a year there are three paydays in a month, and that's when you can actually solve problems. That's when you can get the car registered, or fix the dryer, or get the cat spayed. \n\nThe other 10 months you're doing maintenance and trying to scrape by. Three paycheck months you can actually try to fix problems.",
			"edited": false,
			"author_flair_css_class": null,
			"is_submitter": false,
			"downs": 0,
			"author_flair_richtext": [],
			"author_patreon_flair": false,
			"collapsed_reason": null,
			"body_html": `<div class=\"md\">
				<p>Making financial decisions based around the three paycheck month.
				<br>If you&#39;re paid every two weeks, most months you get two paychecks, and all of your monthly bills and budgeting is based on those two paychecks. But twice a year there are three paydays in a month, and that&#39;s when you can actually solve problems. That&#39;s when you can get the car registered, or fix the dryer, or get the cat spayed. </p>
				\n\n
				<p>The other 10 months you&#39;re doing maintenance and trying to scrape by. Three paycheck months you can actually try to fix problems.</p>
				\n
				</div>`,
			"stickied": false,
			"subreddit_type": "public",
			"can_gild": true,
			"gildings": {},
			"author_flair_text_color": null,
			"score_hidden": false,
			"permalink": "/r/AskReddit/comments/bxgldm/rich_people_of_reddit_who_married_someone/eq7fjta/",
			"num_reports": null,
			"locked": false,
			"name": "t1_eq7fjta",
			"created": 1559874700,
			"subreddit": "AskReddit",
			"author_flair_text": null,
			"collapsed": false,
			"created_utc": 1559845900,
			"subreddit_name_prefixed": "r/AskReddit",
			"controversiality": 0,
			"depth": 0,
			"author_flair_background_color": null,
			"mod_reports": [],
			"mod_note": null,
			"distinguished": null
		}
	]
]